controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

features:
    resource:
        path: ../src/Features/
        namespace: App\Features
    type: attribute
