when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            # Add request headers, cookies, IP address and the authenticated user
            # see https://docs.sentry.io/platforms/php/data-management/data-collected/ for more info
            # send_default_pii: true
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
                - 'Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException'

when@dev:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            # Add request headers, cookies, IP address and the authenticated user
            # see https://docs.sentry.io/platforms/php/data-management/data-collected/ for more info
            # send_default_pii: true
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
                - 'Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException'

