nelmio_cors:
    defaults:
        origin_regex: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_headers: ['Content-Type']
            allow_methods: ['POST', 'OPTIONS']

when@dev:
    nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['http://localhost:1337']

when@prod:
    nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['https://ohdit.com', 'https://www.ohdit.com']
