---
- name: Copying api server nginx configuration
  template:
    src: "ohdit-api.nginx.conf.j2"
    dest: /etc/nginx/sites-enabled/ohdit-api.conf
  notify: restart web services
  become: yes

- name: Copying server nginx configuration
  template:
    src: "ohdit-www.nginx.conf.j2"
    dest: /etc/nginx/sites-enabled/ohdit-www.conf
  notify: restart web services
  become: yes
