name: Ohdit Tests

on: [push]

jobs:
  #############
  # TESTS API #
  #############
  tests-api:
    name: Tests API
    runs-on: ubuntu-latest

    permissions:
      contents: write

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: raphaello
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      # Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Preparing .env file for github
        working-directory: ./api
        run: cp .env.github .env.test.local

      - name: Install composer dependencies
        working-directory: ./api
        run: composer install -n --prefer-dist --optimize-autoloader

      - name: Setup JWT secret
        working-directory: ./api
        run: bin/console lexik:jwt:generate-keypair --overwrite --no-interaction

      # Tests api
      - name: Phpstan
        working-directory: ./api
        run: bin/phpstan --memory-limit=1G

      - name: Ecs
        working-directory: ./api
        run: bin/ecs
        continue-on-error: true

      - name: Rector
        working-directory: ./api
        run: bin/rector process src --dry-run
        continue-on-error: true

      - name: Database setup
        working-directory: ./api
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php  bin/console foundry:load-fixtures all -n --env=test

      - name: Unit and integration tests
        working-directory: ./api
        run: bin/phpunit --testdox --fail-on-warning --fail-on-risky --fail-on-incomplete --fail-on-skipped

      - name: Composer audit
        working-directory: ./api
        run: composer audit

      # Slack notification on failure      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ci'
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'Ohdit'
          SLACK_ICON_EMOJI: ':robot:'
          SLACK_TITLE: Tests Api - Last commit
          SLACK_FOOTER: "“Try not. Do or do not. There is no try.” — Yoda"

  #############
  # TESTS APP #
  #############
  tests-app:
    name: Tests Web App
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install node dependencies
        working-directory: ./app
        run: npm install
      
      # Tests app
      - name: Check linting
        working-directory: ./app
        run: npm run lint
      
      - name: Check Typescript
        working-directory: ./app
        run: npm run typescript
      
      - name: Check Build
        working-directory: ./app
        run: npm run build

      - name: Npm audit app
        working-directory: ./app
        run: npm audit

      # Slack notification on failure      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ci'
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'Ohdit'
          SLACK_ICON_EMOJI: ':scream:'
          SLACK_TITLE: Tests App - Last commit
          SLACK_FOOTER: "“Try not. Do or do not. There is no try.” — Yoda"

  #############
  # TESTS WWW #
  #############
  tests-www:
    name: Tests WWW
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install node dependencies
        working-directory: ./www
        run: npm install
      
      # Tests www
      - name: Linting fixes
        working-directory: ./www
        run: npm run lint
      
      - name: Prettier fixes
        working-directory: ./www
        run: npx prettier src

      - name: Npm audit www
        working-directory: ./www
        run: npm audit

      # Slack notification on failure      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ci'
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'Ohdit'
          SLACK_ICON_EMOJI: ':poop:'
          SLACK_TITLE: Tests WWW - Last commit
          SLACK_FOOTER: "“Try not. Do or do not. There is no try.” — Yoda"